### PR TITLE
Some improvements to CI

### PR DESCRIPTION
**Pull request by giordano**
* add CompatHelper
* reduce frequency of TagBot to once per day
* add scripts to run CI on ARM architectures with Drone CI (see https://discourse.julialang.org/t/testing-on-arm-with-drone-ci/25871, this needs to be activated [here](https://cloud.drone.io/JuliaMath/DecFP.jl/settings) by someone with admin rights in this repository)
* add FreeBSD to Travis
* run Travis only on master, instead of all branches
* cache artifacts on Travis and AppVeyor (see https://discourse.julialang.org/t/recommendation-cache-julia-artifacts-in-ci-services/35484)

### CODE REVIEW

**Comment by stevengj** [comment]
Drone CI is now activated for this repo.  (Doesn't github CI support ARM by now?)

**Comment by giordano** [comment]
> Doesn't github CI support ARM by now?

GitHub Actions provide runners for aarch64, but the problem is that Azure doesn't support this platform, so there are no Github-hosted runners for it

**Comment by stevengj** [comment]
Drone CI seems to be failing these days (see #152).

**Comment by giordano** [comment]
1.4 armv7l is failing because it should specify 1.4.1 instead of 1.4 (which would try to use 1.4.2, but there was no build for armv7l for that version).  The failure in v1.3 is more worrying, as it's a segmentation fault in `libbid.so`, but maybe it's this package's fault?

**Comment by stevengj** [comment]
Should we try to use 1.7.2 rather than 1.4.x?

**Comment by giordano** [comment]
> Should we try to use 1.7.2 rather than 1.4.x?

Yes, although we need to check whether we have a build for armv7l.

I just tried to run DecFP with an i686 Julia (you can run it on x86_64 as well) and I got the same error:
```
julia> using DecFP
[ Info: Precompiling DecFP [55939f99-70c6-5e9b-8bb0-5071ed7d61fd]

signal (11): Segmentation fault
in expression starting at /home/mose/.julia/packages/DecFP/XcoGq/src/DecFP.jl:290
__bid32_from_string at /home/mose/.julia/artifacts/2f1a326980200b143068522db21146532204f215/lib/libbid.so (unknown line)
_parse at /home/mose/.julia/packages/DecFP/XcoGq/src/DecFP.jl:299
```
So it looks like this package is currently broken with any 32-bit platform

**Pull request merged**
