### PR TITLE
Update to Version 2.0 Update 2

### LINKED ISSUE #47: exp10(Dec128(0)) produces incorrect result
```
julia> exp10(Dec32(0))
+1E+0

julia> exp10(Dec64(0))
+1E+0

julia> exp10(Dec128(0))
+0E+0
```

### PR DESCRIPTION
**Pull request by jmkuhn**
Fixes #47. Supersedes #90.

### CODE REVIEW

**Comment by jmkuhn** [comment]
For 64 bit Windows this error occurs in Julia 0.7 and 1.0 but not 1.1.  I'll poke around a bit more to see what I can find.

```
julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, ivybridge)

julia> Dec128(1) * im
0.0 + 1.0im

julia> versioninfo()
Julia Version 1.0.4
Commit 38e9fb7f80 (2019-05-16 03:38 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)

julia> Dec128(1) * im
ERROR: ReadOnlyMemoryError()
Stacktrace:
 [1] copysign at C:\Users\john\julia_dev\DecFP_v2_mynew\dev\DecFP\src\DecFP.jl:382 [inlined]
 [2] * at .\bool.jl:118 [inlined]
 [3] * at .\bool.jl:120 [inlined]
 [4] *(::Dec128, ::Complex{Bool}) at .\complex.jl:299
 [5] top-level scope at none:0
```

**Comment by jmkuhn** [comment]
I don't know where to go from here:
```
julia> versioninfo()
Julia Version 1.0.4
Commit 38e9fb7f80 (2019-05-16 03:38 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)

julia> x = Dec128(1)
1.0

julia> copysign(zero(x), x)
0.0

julia> f(x) = copysign(zero(x), x)
f (generic function with 1 method)

julia> f(x)
ERROR: ReadOnlyMemoryError()
Stacktrace:
 [1] copysign at C:\Users\john\julia_dev\DecFP_v2_mynew\dev\DecFP\src\DecFP.jl:382 [inlined]
 [2] f(::Dec128) at .\REPL[53]:1
 [3] top-level scope at none:0
```

**Comment by jmkuhn** [comment]
Rerun CI.

**Comment by jmkuhn** [comment]
As we discussed earlier this week, this fails for 64 bit Windows running Julia 0.7 and 1.0.  Passes for 1.1 and nightly.  See comment https://github.com/JuliaMath/DecFP.jl/pull/96#issuecomment-495280204 for the expression that causes `ReadOnlyMemoryError()`.  Note that expression only causes an error when run in a function.  When run directly in the REPL it runs correctly.

**Comment by stevengj** [comment]
I don't mind updating this only for Julia 1.1 or later — older Julia users can continue to use the old version.

(I wish that we could be more confident that the problem is a bug that was fixed in 1.1, however, rather than a bug in DecFP that only currently appears in Julia 1.0.   We could try a bisection search, but that requires someone who can actually build Julia on Windows.)

**Comment by jmkuhn** [comment]
I've never built Julia on Windows or run a git bisection, but I'll give it a try.

**Comment by jmkuhn** [comment]
Closing in favor of #106.

**Pull request closed without merging**
