### PR TITLE
update CI

### PR DESCRIPTION
**Pull request by stevengj**
Test 32-bit version (on Linux) and latest Julia release (instead of 1.4).

(I deleted DecFP from AppVeyor today, but for some reason it is still running…)

### CODE REVIEW

**Comment by stevengj** [comment]
@jmkuhn, any ideas on the CI failures?

**Comment by giordano** [comment]
If we want to keep a 32-bit platform in the tests, using i686 in GitHub Actions may be a bit easier than using armv7l in drone.  See for example https://github.com/julia-actions/setup-julia/blob/b69122e25a41dfa3fc1b74a4e8c21fd842fc57c7/README.md#32-bit-julia.   However we also need to fix the error, which I think is coming from https://github.com/JuliaMath/DecFP.jl/blob/6ccece6b0df79796ca7a7303117fad9ca8f5809b/src/DecFP.jl#L322-L323

**Comment by giordano** [comment]
> (I deleted DecFP from AppVeyor today, but for some reason it is still running…)

The webhook for AppVeyor was still active, I deleted it from the settings of the repo

**Comment by giordano** [comment]
Reading the code of the C library isn't much fun, but I think the signature of the `__bid32_from_string` function is
```c
unsigned __bid32_from_string (char *ps,
                              unsigned int rnd_mode,
                              unsigned int *pfpsf,
                              unsigned int exc_mask,
                              void *BID_pexc_info);
```
does it sound right?

**Comment by stevengj** [comment]
Seems to be broken on all 32-bit plafforms. 😢

**Comment by stevengj** [comment]
I just compiled it using the [Yggdrasil build flags](https://github.com/JuliaPackaging/Yggdrasil/blob/master/D/DecFP/build_tarballs.jl) plus `-save-temps` to save the preprocessed output, and the prototype is:
```c
typedef unsigned int _IDEC_round;
typedef unsigned int _IDEC_flags;

    extern BID_UINT32 __bid32_from_string (char *ps
                                      , _IDEC_round rnd_mode , _IDEC_flags *pfpsf
                                                                      );
```

**Comment by stevengj** [comment]
One difference is that Intel declares the return type `BID_UINT32` as `unsigned`, whereas we use a `struct`.

Maybe this will be fixed by #91?

**Comment by giordano** [comment]
Maybe we can remove the 32-bit platforms from this PR and try to rebase #91 and run github actions for x86 there?

**Comment by stevengj** [comment]
I'm inclined to merge this PR since it's just exposing breakage, it's not the source of it.   Then maybe we can rebase #91.

**Comment by giordano** [comment]
I'd suggest removing the armv7l from drone though, the build for v1.7 was stalling

**Comment by giordano** [comment]
Ok, I'll do a PR :smile:

**Comment by stevengj** [comment]
I've rebased #91, let's see how it goes.

**Pull request merged**
